# Generated by Django 4.2.5 on 2023-10-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_table',
            name='date',
            field=models.DateField(default='1990-3-4'),
            preserve_default=False,
        ),
    ]
